#!/bin/bash
set -e

# Figure out where this script is located.
SELFDIR="`dirname \"$0\"`"
SELFDIR="`cd \"$SELFDIR\" && pwd`"

cd "$SELFDIR"
. lib/wrapper-common.sh

if ! [ -e db/$RAILS_ENV.sqlite3 ];then
    "$SELFDIR/lib/ruby/bin/bundle" exec rake db:migrate
fi
exec "$SELFDIR/lib/ruby/bin/ruby" -rbundler/setup "$SELFDIR/lib/app/bin/rails" s $*
